return {
  -- {
  --   "Julian/vim-textobj-variable-segment",
  --   dependencies = { "kana/vim-textobj-user" },
  -- },
  -- {
  --   "nvim-treesitter/nvim-treesitter-textobjects",
  --   lazy = true,
  --   opts = {
  --     textobjects = {
  --       select = {
  --         enable = true,
  --         lookahead = true,
  --         keymaps = {
  --           ["a="] = { query = "@assignment.outer", desc = "Select outer part of an assignment" },
  --           ["i="] = { query = "@assignment.inner", desc = "Select inner part of an assignment" },
  --           ["=l"] = { query = "@assignment.lhs", desc = "Select left hand side of an assignment" },
  --           ["=r"] = { query = "@assignment.rhs", desc = "Select right hand side of an assignment" },
  --         },
  --       },
  --     },
  --   },
  -- },
}
